name: uas_sosmed
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  flutter_slider_drawer: ^2.1.1
  line_icons: ^2.0.1
  firebase_core: ^1.20.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/logo/
  uses-material-design: true
