// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNbJdWQEPL8W1iJHHMiOlG9OUWgzoA-WI',
    appId: '1:817345410698:web:78466f4a5c7048510c1f73',
    messagingSenderId: '817345410698',
    projectId: 'my-lambe-app',
    authDomain: 'my-lambe-app.firebaseapp.com',
    storageBucket: 'my-lambe-app.appspot.com',
    measurementId: 'G-1F2F4E2V7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANiYjtrxT6lSmxxz75AYYh19hWEC67MMI',
    appId: '1:817345410698:android:f35c377dbbf21f580c1f73',
    messagingSenderId: '817345410698',
    projectId: 'my-lambe-app',
    storageBucket: 'my-lambe-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD6FMUdHAGfEqwhE3yGrj2CGK1C3mHNlE',
    appId: '1:817345410698:ios:b57ccc9e8c808ee10c1f73',
    messagingSenderId: '817345410698',
    projectId: 'my-lambe-app',
    storageBucket: 'my-lambe-app.appspot.com',
    iosClientId:
        '817345410698-t0gb6bf5msgdvdvqd6u44icvhgf378r0.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasSosmed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD6FMUdHAGfEqwhE3yGrj2CGK1C3mHNlE',
    appId: '1:817345410698:ios:b57ccc9e8c808ee10c1f73',
    messagingSenderId: '817345410698',
    projectId: 'my-lambe-app',
    storageBucket: 'my-lambe-app.appspot.com',
    iosClientId:
        '817345410698-t0gb6bf5msgdvdvqd6u44icvhgf378r0.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasSosmed',
  );
}
